/*
===============================================================================
04 - Magnitude Analysis
===============================================================================
Purpose:
    Analyze measures by dimensions, such as customers by country,
    products by category, and sales by product/customer attributes.
===============================================================================
*/

USE DataWarehouseAnalytics;
GO

-- Find the total number of customers by country.
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find the total number of customers by gender.
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find the total number of products by category.
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- Find the average product cost by category.
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- Find the total revenue generated by each product category.
SELECT
    p.category,
    SUM(s.sales_amount) AS total_sales
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p
    ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_sales DESC;

-- Find the total revenue generated by each customer.
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(s.sales_amount) AS total_sales
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
    ON s.customer_key = c.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_sales DESC;

-- Find the distribution of sold items across countries.
SELECT
    c.country,
    SUM(s.quantity) AS total_sold_quantity
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
    ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_quantity DESC;
